# Generated by Django 4.1.2 on 2022-11-18 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_listing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listing',
            new_name='Item',
        ),
    ]
