# Generated by Django 4.1.2 on 2022-12-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_item_startingbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_img',
            field=models.ImageField(default='path/to/my/default/image.jpg', upload_to='images'),
        ),
    ]
