# Generated by Django 4.1.2 on 2022-12-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_item_item_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('miscellaneous', 'Miscellaneous'), ('books', 'Books'), ('clothing', 'Clothing'), ('electronics', 'Electronics'), ('furniture', 'Furniture')], default='miscellaneous', max_length=64),
        ),
    ]
