# Generated by Django 4.1.2 on 2023-01-11 23:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_item_category_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='watchlist_user',
            field=models.ManyToManyField(blank=True, related_name='watchlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
