# Generated by Django 4.1.2 on 2023-02-02 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_bid_amount_bid_listing_bid_timestamp_bid_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
