# Generated by Django 4.1.2 on 2023-02-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_comment_comment_comment_listing_comment_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
